name: flat-tomorrow
on:
  workflow_dispatch: {}
  schedule:
    - cron: 20 18 * * *
  push:
    paths:
      - .github/workflows/flat-tomorrow.yml
      - ./cleaning-electricity-price-tomorrow.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.esios.ree.es/archives/70/download_json
          downloaded_filename: electricity-price-api-tomorrow.json
          authorization: ${{ secrets.API_TOKEN }}
          postprocess: ./cleaning-electricity-price-tomorrow.js
